# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time+
name: Display Project Directory and Files

on:
  # push:
  #   branches-ignore: 
  #   - 'main'
  #   - 'release*'
  # pull_request:
  #   branches-ignore: 
  #   - 'main'
  #   - 'release*'
  push:
    branches: 
    - 'main'
    - 'release*'
    - '*'
  pull_request:
    branches: 
    - 'main'
    - 'release*'
    - '*'

jobs:
  build:
    name: Unit Test-Build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_DATABASE: Lendit_Book_Kiosk
          MYSQL_USER: admin
          MYSQL_PASSWORD: developer
          MYSQL_ROOT_PASSWORD: developer
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
      
